### PR TITLE
Updated Storage Account Section #374 #375

### PR DESCRIPTION
**Pull request by nsshaddox**
This update is to get the azure section on the same level as the AWS section.

- Removed most of the hand holding code snippets.
- Added Deliverables

### CODE REVIEW

**Comment by jburns24** [comment]
@densellp @nsshaddox I like what I am seeing, a couple of quick requests.
1) please review the front-matter for each exercise and adjust if need be (I would expect exercise estimates increase with the removal of the hand holding)
2) As a comment in GH can you answer the deliverables you are adding. I am interested in knowing what lesson you are trying to get across with each deliverable.

**Comment by densellp** [comment]
Not a bad plan, I will look into that

**Comment by densellp** [comment]
- What is the benefit of using the CLI vs the UI?
* In the cli you have access to a wide variety of commands to choose from and all of the examples at your fingertips. Not to say the UI is all bad, but with the CLI you gain instant access to whatever command you need with a simple -h flag.
- What is the purpose of a resource group and why is it important?
* A resource group can consolidate all resources of a project or group of projects. This is useful as you don’t need to worry about where your resources live and what exactly you are consuming. It is all easily accessible and can be torn down easily.
- What key advantages did you discover about Azure Storage Accounts during this exercise?
* Storage accounts can do all sorts of things, the example we used was for for static website hosting, but can group all storage types such as blobs, files, queues, and tables. The static website was hosted in a storage blob, which does support static hosting. Storage accounts can also store files that need to be stored remotely such as configuration and state files.
- What were the key considerations when creating the Azure CDN profile for the website?
* CDN needs a couple things to function properly. The obvious ones are the resource group and name, but also need an origin of the application, a profile, and an optional flag of enable compression, which allows the CDN to only server files that are needed instead of serving all files at once. The compression will also ensure that files can be send quickly.

**Comment by nsshaddox** [comment]
> @densellp @nsshaddox I like what I am seeing, a couple of quick requests.
> 
> 1. please review the front-matter for each exercise and adjust if need be (I would expect exercise estimates increase with the removal of the hand holding)

The time estimate more accurate the way the this section is structured now. With the hand holding, we went through this section within about hour. Four hours seems pretty reasonable for how we have changed it. Most of it is just using the command line tool to discover the correct command that they need. Other parts include links to documentation that will give them some direction in case they can't find the command.

**Review by jburns24 — APPROVED** [review]
:shipit:

**Pull request merged**
